### ISSUE TITLE
BDS3 data processing?

### ISSUE THREAD

**Issue by Gaoxinlove** [zcytju/M_GIM#1]
The BDS in 'sate_mark' struct has 16 satellites. Have you ever processed BDS-3 data, or in the updated version?  

All in all, thanks for your opening, it's a powerful tool for ionospheric researchers!

**Comment by zcytju** [comment]
Only the BDS-2 data is considered in current version. Due to the limited station numbers containing BDS-3 before, the BDS-3 system was not considered. Actually, BDS-3 can be considered as a separate system adding into the process, and the BDS-3 related satellite DCBs can be estimated simultaneously. The version containing BDS-3 data may take some time to update. Thanks for your attention.
